// Jenkins Pipeline (Jenkinsfile)
pipeline {
    agent any

    environment {
        APP_DIR = '/home/ubuntu/fashionlink'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Compose Deploy') {
            steps {
                sh """
                    cd ${APP_DIR}
                    docker-compose down
                    docker-compose build --no-cache
                    docker-compose up -d
                """
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}